### PR TITLE
feat: upgrade to @hapi

### PR DESCRIPTION
**Pull request by mkg20001**
This upgrades all packages and switches namespaces for old hapi packages to new namespace, to fix warnings and security issues.

### CODE REVIEW

**Comment by mkg20001** [comment]
Joi seems to have ditched the `Joi.validate` error which makes some tests fail

Also sinon is complaining about double-wrapped methods

Among other random test failures

**Comment by JKHeadley** [comment]
@mkg20001 This is great! Thanks for handling this. Definitely good to have loggin updated until https://github.com/JKHeadley/rest-hapi/issues/150 is handled.

Once we can get these tests fixed I'll go ahead and merge.

**Comment by mkg20001** [comment]
@JKHeadley Some deps are still downgraded (since I tried fixing the tests this way, but seems that most are broken because of hapi API changes). Also joi-objectid has a problem with the new joi, so that is forked now as well.

Btw, I have sent an email to the owner of the loggin package and CC'd npm support, so if it won't get updated I'll possibly get to take it over next month.

I'll do the same one for joi-objectid, since peeble is now bought by fitbit and I doubt they're doing much opensource for it now.

**Comment by JKHeadley** [comment]
@mkg20001 Awesome about loggin and joi-objectId, def let me know how it goes!

**Comment by mkg20001** [comment]
@JKHeadley I now own loggin (and the underlying gh-organization fistlabs)

In case of joi-objectid: I'll let the pr idle until the end of the month before contacting support.

**Comment by mkg20001** [comment]
@JKHeadley Besides that, could you look into the tests? I'm clueless as to what is broken, but since you've written it you might be able to get a better idea.

**Comment by JKHeadley** [comment]
Great news! Yeah I'll try to look into the tests.

**Comment by mkg20001** [comment]
Note that a possible bugfix for joi errors that include something about `$._.alternatives` is to wrap the Joi object `{key: Joi.string()}` with the joi function `Joi.object({key: Joi.string()}`

**Comment by mkg20001** [comment]
I've sent out the email to joi-objectid now instead of waiting forever. Response is that it's a bit complicated since the company that owns it is now gone.

**Comment by JKHeadley** [comment]
Pushed some changes to fix the tests. I'll leave it up to you, but I think for now keeping Joi to v14 will be a good idea so we can merge the rest. The jump from 14 to 16 looks to be pretty major:
https://github.com/hapijs/joi/issues/2037

Maybe we can tackle that one in a different PR.

**Comment by mkg20001** [comment]
Sure, sounds pretty reasonable
Since they're both backwards compatible this shouldn't be much of an issue

**Comment by mkg20001** [comment]
So LGTM?

**Comment by JKHeadley** [comment]
Merged! Thanks for all the work! 👍

**Pull request merged**
