### PR TITLE
Feature/hapi server config

### PR DESCRIPTION
**Pull request by shiva**
1. Minor commit to include code-cov as part of dev dependency
2. Support for baseUrl in REST-HAPI
3. pass through hapi-swagger configuration as an option. 
4. Support all legacy options, but those get overridden when config.swaggerOptions is set (as per hapi-swagger documentation).
5. Additionally some swaggerOptions are over-written.

### CODE REVIEW

**Comment by shiva** [comment]
Note: The build actually passed, but there seems to be a stage that pushes to this repo, and that step failed.

**Comment by JKHeadley** [comment]
@shiva made some slight modifications. Apologies, it looks like I misinformed you. To set a prefix for all rest-hapi routes the correct way would be to use the correct hapi register option . For example, when you register rest-hapi you could do this like so:

```js
    await server.register({
      plugin: RestHapi,
      options: {
        mongoose: mongoose,
        config: config,
      },
      routes: {
        prefix: '/test'
      }
    })
```

**Comment by shiva** [comment]
This make more sense. Would you like me to squash these changes, and reduce the amount of churn before you merge?

**Comment by JKHeadley** [comment]
@shiva Yes a squash would be great. First though I would like to make sure the docs get updated to reflect the changes. Feel free to update them if you like, or I will try to get to it soon. Thanks!

**Comment by shiva** [comment]
@JKHeadley Here is the newly cleaned up commits. I will make another commit for updating the docs and get back

**Comment by shiva** [comment]
Updated documentation as well. @JKHeadley  Let me know if you need anything else before merge

**Comment by JKHeadley** [comment]
Awesome, thanks!

**Pull request merged**
