### PR TITLE
Add possibility to disable SwaggerUI via an enviroment variable

### PR DESCRIPTION
**Pull request by lucarp**
This pull request adds the possibility to choose if you want to use SwaggerUI or not. In my particular case, I don't want SwaggerUI in production environment. 

By default, the UI is enabled. However, if you pass SWAGGER_DOCS='disable' to process.env, then Swagger is disabled. This way, it maintains compatibility with current version....

### CODE REVIEW

**Comment by JKHeadley** [comment]
Great idea! Would it work for your use case if the option was added to `config.js` (something like `config.enableSwaggerUI = true;`) rather than using an env var? It would keep things more consistent. This ultimately could still be set by an env var by the project that is implementing rest-hapi.

**Comment by lucarp** [comment]
Sounds perfect! I’ll submit a new pull request!
Em qui, 15 de mar de 2018 às 15:25, Justin Headley <notifications@github.com>
escreveu:

**Comment by lucarp** [comment]
I have committed the code including config.enableSwaggerUI = true

**Comment by JKHeadley** [comment]
Looks great! Thanks!

**Pull request merged**
